main.ml: only block signals on Posix systems
The change to block signals unadvertedly broke F* on Windows, which
would exit on startup with:

    Fatal error: exception (Invalid_argument "Unix.sigprocmask not implemented")