removed ticks when tyVars are retained in ML as termVars.
This change seems to preserve passing all tests, and hence can be merged to master:

Error: 35 errors were reported (see above)
Success: 35 failures were expected
make[2]: Leaving directory '/home/t-aban/FStar/examples/unit-tests'
make[1]: Leaving directory '/home/t-aban/FStar/examples'