MD5 compiles, but doesn't run, as expected. Tried to move some definitions to the restricted API of array. renamed [hs]create to [hs]createSeq. These were used for convenience at some places in MD5. These functions can be implemented over the primitive interface. Added [hs]create as discussed.
$ ./md5
Fatal error: exception Failure("Not yet implemented:MachineWord.fromNat")